# Generated by Django 3.2.9 on 2021-11-18 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.IntegerField(help_text='Идентификатор', primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('is_manager', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'ordering': ['is_manager', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.IntegerField(help_text='Идентификатор заявки', primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Введите заголовок заявки', max_length=256)),
                ('text', models.TextField(help_text='Введите текст заявки', max_length=4096)),
                ('priority', models.CharField(blank=True, choices=[('3', 'Низкий'), ('2', 'Средний'), ('1', 'Высокий'), ('0', 'Наивысший')], default='2', help_text='Приоритет заявки', max_length=1)),
                ('status', models.CharField(blank=True, choices=[('n', 'Новая'), ('w', 'В работе'), ('r', 'На проверке'), ('c', 'Завершена')], default='n', help_text='Статус заявки', max_length=1)),
                ('category', models.CharField(blank=True, choices=[('1', 'Сантехника'), ('2', 'Электрика'), ('3', 'Ремонтные работы'), ('4', 'Лифт'), ('5', 'Общедомовая территория')], default='1', help_text='Категория заявки', max_length=1)),
                ('assigned_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignee', to='inquiries.person')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiry_author', to='inquiries.person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.IntegerField(help_text='Идентификатор', primary_key=True, serialize=False)),
                ('text', models.TextField(help_text='Введите текст комментария', max_length=4096)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inquiries.person')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inquiries.todo')),
            ],
        ),
    ]
