# Generated by Django 3.2.9 on 2021-11-21 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user', verbose_name='Пользователь')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=150)),
                ('phone_number', models.CharField(max_length=100)),
                ('is_manager', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['is_manager', 'user'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.IntegerField(help_text='Идентификатор помещения', primary_key=True, serialize=False)),
                ('street', models.CharField(help_text='Улица', max_length=100)),
                ('building', models.IntegerField(help_text='Номер дома')),
                ('number', models.IntegerField(help_text='Номер помещения')),
                ('entrance', models.IntegerField(help_text='Номер подъезда')),
                ('flat', models.IntegerField(help_text='Номер этажа')),
                ('area', models.IntegerField(help_text='Площадь помещения')),
                ('priority', models.CharField(blank=True, choices=[('0', 'Жилое'), ('1', 'Коммерческое')], default='0', help_text='Тип помещения', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Текст варианта голосования', max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.IntegerField(help_text='Идентификатор заявки', primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Введите заголовок заявки', max_length=256)),
                ('text', models.TextField(help_text='Введите текст заявки', max_length=4096)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_author', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inquiries.selection')),
                ('survey', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inquiries.survey')),
                ('voter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.IntegerField(help_text='Идентификатор заявки', primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Введите заголовок заявки', max_length=256)),
                ('text', models.TextField(help_text='Введите текст заявки', max_length=4096)),
                ('priority', models.CharField(blank=True, choices=[('3', 'Низкий'), ('2', 'Средний'), ('1', 'Высокий'), ('0', 'Наивысший')], default='2', help_text='Приоритет заявки', max_length=1)),
                ('status', models.CharField(blank=True, choices=[('n', 'Новая'), ('w', 'В работе'), ('r', 'На проверке'), ('c', 'Завершена')], default='n', help_text='Статус заявки', max_length=1)),
                ('category', models.CharField(blank=True, choices=[('1', 'Сантехника'), ('2', 'Электрика'), ('3', 'Ремонтные работы'), ('4', 'Лифт'), ('5', 'Общедомовая территория')], default='1', help_text='Категория заявки', max_length=1)),
                ('assignee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignee', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='todo_author', to='inquiries.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='selection',
            name='survey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inquiries.survey'),
        ),
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inquiries.property')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.BinaryField(help_text='Изображение')),
                ('inquiry', models.ForeignKey(help_text='Заявка', on_delete=django.db.models.deletion.CASCADE, to='inquiries.todo')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Введите текст комментария', max_length=4096)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inquiries.todo')),
            ],
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.IntegerField(help_text='Идентификатор заявки', primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Введите заголовок заявки', max_length=256)),
                ('text', models.TextField(help_text='Введите текст заявки', max_length=4096)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcement_author', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
