# Generated by Django 3.2.9 on 2021-11-18 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0002_alter_person_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Текст варианта голосования', max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.IntegerField(help_text='Идентификатор заявки', primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Введите заголовок заявки', max_length=256)),
                ('text', models.TextField(help_text='Введите текст заявки', max_length=4096)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_author', to='inquiries.person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='todo_author', to='inquiries.person'),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inquiries.person')),
                ('selection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inquiries.selection')),
                ('survey', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inquiries.survey')),
            ],
        ),
        migrations.AddField(
            model_name='selection',
            name='survey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inquiries.survey'),
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.IntegerField(help_text='Идентификатор заявки', primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Введите заголовок заявки', max_length=256)),
                ('text', models.TextField(help_text='Введите текст заявки', max_length=4096)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcement_author', to='inquiries.person')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
