# Generated by Django 3.2.9 on 2021-12-06 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inquiries', '0002_alter_inquiry_inquiry_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='inquiry_creator',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
