# Generated by Django 3.2.9 on 2021-11-19 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0003_auto_20211118_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.IntegerField(help_text='Идентификатор помещения', primary_key=True, serialize=False)),
                ('number', models.IntegerField(help_text='Номер помещения')),
                ('entrance', models.IntegerField(help_text='Номер подъезда')),
                ('flat', models.IntegerField(help_text='Номер этажа')),
                ('area', models.IntegerField(help_text='Площадь помещения')),
                ('priority', models.CharField(blank=True, choices=[('0', 'Жилое'), ('1', 'Коммерческое')], default='0', help_text='Тип помещения', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inquiries.person')),
                ('property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inquiries.property')),
            ],
        ),
    ]
