# Generated by Django 3.2.9 on 2021-11-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0004_ownership_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='building',
            field=models.IntegerField(default=22, help_text='Номер дома'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='street',
            field=models.CharField(default='Революции', help_text='Улица', max_length=100),
            preserve_default=False,
        ),
    ]
