# Generated by Django 3.2.9 on 2021-11-19 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0005_auto_20211119_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownership',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inquiries.person'),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inquiries.property'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inquiries.person'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='selection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inquiries.selection'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='survey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inquiries.survey'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.BinaryField(help_text='Изображение')),
                ('inquiry', models.ForeignKey(help_text='Заявка', on_delete=django.db.models.deletion.CASCADE, to='inquiries.todo')),
            ],
        ),
    ]
