# Generated by Django 3.2.9 on 2022-01-24 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0006_auto_20220103_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='poll_open',
        ),
    ]
