# Generated by Django 3.2.9 on 2022-02-01 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0007_remove_poll_poll_open'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_title', models.CharField(help_text='Заголовок информационного сообщения', max_length=256)),
                ('info_text', models.TextField(help_text='Текст информационного сообщения', max_length=4096)),
            ],
        ),
    ]
