# Generated by Django 3.2.9 on 2021-12-11 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0008_auto_20211211_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='todo_priority',
            field=models.CharField(blank=True, choices=[('3', 'Низкий'), ('2', 'Средний'), ('1', 'Высокий'), ('0', 'Наивысший')], default='2', help_text='Приоритет заявки', max_length=1),
        ),
        migrations.AlterField(
            model_name='todo',
            name='todo_status',
            field=models.CharField(blank=True, choices=[('n', 'Новая'), ('w', 'В работе'), ('r', 'На проверке'), ('c', 'Завершена')], default='n', help_text='Статус заявки', max_length=1),
        ),
    ]
