# Generated by Django 3.2.9 on 2021-12-21 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0009_auto_20211211_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='inquiry_update_date',
            field=models.DateTimeField(help_text='Дата обновления заявки', null=True),
        ),
    ]
