# Generated by Django 3.2.9 on 2022-02-01 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0009_alter_info_info_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='info_title',
            field=models.CharField(help_text='Заголовок информационного сообщения', max_length=256),
        ),
    ]
