# Generated by Django 3.2.9 on 2022-02-02 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0010_alter_info_info_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('attachment_id', models.AutoField(help_text='Идентификатор вложения', primary_key=True, serialize=False)),
                ('file', models.ImageField(upload_to='')),
                ('inquiry', models.ForeignKey(help_text='Заявка', on_delete=django.db.models.deletion.CASCADE, to='inquiries.inquiry')),
            ],
        ),
    ]
