# Generated by Django 3.2.9 on 2021-12-21 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0010_inquiry_inquiry_update_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_creation_datetime',
            new_name='comment_created_at',
        ),
        migrations.RenameField(
            model_name='inquiry',
            old_name='inquiry_creation_date',
            new_name='inquiry_created_at',
        ),
        migrations.RenameField(
            model_name='inquiry',
            old_name='inquiry_update_date',
            new_name='inquiry_updated_at',
        ),
    ]
