# Generated by Django 3.2.9 on 2022-02-08 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0014_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ForeignKey(blank=True, help_text='Фотография профиля', null=True, on_delete=django.db.models.deletion.CASCADE, to='inquiries.file'),
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
    ]
