# Generated by Django 3.2.9 on 2022-02-08 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0015_auto_20220208_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.OneToOneField(blank=True, help_text='Фотография профиля', null=True, on_delete=django.db.models.deletion.CASCADE, to='inquiries.file'),
        ),
    ]
